# Generated by Django 5.1.5 on 2026-02-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_deviceevent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicaldevice",
            name="ce_marking",
        ),
        migrations.AddField(
            model_name="category",
            name="calibration_interval_months",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="dguv3_interval_months",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="mtk_interval_months",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="stk_interval_months",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
