# Generated by Django 5.1.5 on 2026-03-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_seed_default_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceappointment',
            name='appointment_type',
            field=models.CharField(choices=[('calibration', 'Kalibrierung'), ('maintenance_mtk', 'Wartung-MTK'), ('maintenance_stk', 'Wartung-STK'), ('maintenance_dguv3', 'Wartung-DGUV3'), ('other', 'Sonstiges')], default='maintenance_mtk', max_length=30),
        ),
    ]
