# Generated by Django 5.1.5 on 2026-03-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_deviceappointment_appointment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceappointment',
            options={'ordering': ['completed', 'due_date', '-performed_date']},
        ),
        migrations.AddField(
            model_name='deviceappointment',
            name='performed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Durchgeführt am'),
        ),
        migrations.AlterField(
            model_name='deviceappointment',
            name='appointment_type',
            field=models.CharField(choices=[('calibration', 'Kalibrierung'), ('maintenance_mtk', 'Wartung-MTK'), ('maintenance_stk', 'Wartung-STK'), ('maintenance_dguv3', 'Wartung-DGUV3'), ('repair', 'Reparatur / Instandsetzung'), ('instruction', 'Einweisung / Schulung'), ('validation', 'Validierung'), ('software_update', 'Software-Update'), ('other', 'Sonstiges / Ereignis')], default='maintenance_mtk', max_length=30),
        ),
        migrations.AlterField(
            model_name='deviceappointment',
            name='due_date',
            field=models.DateField(verbose_name='Fällig am'),
        ),
        migrations.DeleteModel(
            name='DeviceEvent',
        ),
    ]
