# Generated by Django 5.1.5 on 2026-03-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_deviceappointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceappointment',
            name='appointment_type',
            field=models.CharField(choices=[('calibration', 'Kalibrierung'), ('maintenance_mtk', 'Wartung-MTK'), ('maintenance_stk', 'Wartung-STK'), ('maintenance_dguv3', 'Wartung-DGUV3'), ('repair', 'Reparatur'), ('instruction', 'Einweisung'), ('validation', 'Validierung'), ('software_update', 'Software-Update'), ('other', 'Sonstiges')], default='maintenance_mtk', max_length=30),
        ),
    ]
