# Generated by Django 5.1.5 on 2026-05-28 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_deviceappointment_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydocument',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inventory.medicaldevice', verbose_name='Spezifisches Gerät'),
        ),
    ]
