# Generated by Django 5.1.5 on 2026-05-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_categorydocument_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydocument',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
