# Generated by Django 5.1.5 on 2026-08-17 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_categorydocument_document_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='inventory.medicaldevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
