# Generated by Django 5.1.5 on 2026-08-20 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_deviceauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceappointment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='appointment_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'png', 'jpg'])], verbose_name='Dokument'),
        ),
        migrations.DeleteModel(
            name='CategoryDocument',
        ),
    ]
